DB_CONFIG = {
    "oracle": {
        "substr": "SUBSTR",
        "error_trigger": "TO_CHAR(1/0)",
        "from_dual": " FROM dual",
        "sleep": "DBMS_PIPE.RECEIVE_MESSAGE(('a'),{delay})",
        "concat": "||",
        "comment": "--",
        "limit_one": "WHERE ROWNUM=1",
    },
    "mysql": {
        "substr": "SUBSTRING",
        "error_trigger": "1/0",
        "from_dual": "",
        "sleep": "SLEEP({delay})",
        "concat": "CONCAT",
        "comment": "#",
        "limit_one": "LIMIT 1",
    },
    "postgresql": {
        "substr": "SUBSTRING",
        "error_trigger": "1/0",
        "from_dual": "",
        "sleep": "pg_sleep({delay})",
        "concat": "||",
        "comment": "--",
        "limit_one": "LIMIT 1",
    },
    "mssql": {
        "substr": "SUBSTRING",
        "error_trigger": "1/0",
        "from_dual": "",
        "sleep": "WAITFOR DELAY '0:0:{delay}'",
        "concat": "+",
        "comment": "--",
        "limit_one": "TOP 1",
    },
    "sqlite": {
        "substr": "SUBSTR",
        "error_trigger": "1/0",
        "from_dual": "",
        "sleep": "",
        "concat": "||",
        "comment": "--",
        "limit_one": "LIMIT 1",
    },
    "mariadb": {
        "substr": "SUBSTRING",
        "error_trigger": "1/0",
        "from_dual": "",
        "sleep": "SLEEP({delay})",
        "concat": "CONCAT",
        "comment": "#",
        "limit_one": "LIMIT 1",
    },
}
